WebAppSastiServices/Models/Email.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppSastiServices.Models
{
    public class Email
    {

        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int Age { get; set; }
        public bool isNewlyEnrolled { get; set; }
        public string Password { get; set; }
    }
}

WebAppSastiServices/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppSastiServices.Models;
using WebAppSastiServices.Models.DB;
    

namespace WebAppSastiServices.Controllers
{
    public class AdminDashboardController : Controller
    {
        SastaServicesDBEntities db = new SastaServicesDBEntities();
        // GET: AdminDashboard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LatestActOrders()
        {
            db.Configuration.ProxyCreationEnabled = false;

            //---------Single Table Data---------
            //IList<TRNCustomerOrder> orders = db.TRNCustomerOrders.
            //    Where(s => s.STPStatu.Description == "Not Availed").
            //    ToList<TRNCustomerOrder>();
           

            var result = (from o in db.TRNCustomerOrders
                                         join t in db.STPPrefferedTimes on o.preferredTimeID equals t.ID
                                          join s in db.STPServiceTypes on o.ServiceTypeId equals s.ID
                                          join st in db.STPStatus on o.OrderStatusId equals st.ID
                                          select new
                                          {
                                              OrderId = o.OrderId,
                                              CustomerName = o.CustomerName,
                                              Contact = o.Contact,
                                              Address = o.Address,
                                              Description = s.ServiceTypeName,
                                              TimeRange = t.TimeRange,
                                              preferredDate = o.preferredDate.ToString(),
                                              status = st.Description,
                                              CreateOn= o.CreateOn.ToString()
                                          }).ToList();


            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Email()
        {
            return View();
        }
        public ActionResult Vendor()
        {
            return View();
        }
        //public ActionResult Supplier()
        //{
        //    return View();
        //}
        public ActionResult AdminProfile()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult LockScreen()
        {
            return View();
        }
        public ActionResult Invoice()
        {
            return View();
        }
        public ActionResult InvoiceReport()
        {
            var result = (from o in db.TRNCustomerOrders
                          join t in db.STPPrefferedTimes on o.preferredTimeID equals t.ID
                          join s in db.STPServiceTypes on o.ServiceTypeId equals s.ID
                          join st in db.STPStatus on o.OrderStatusId equals st.ID
                          join f in db.STPServicesFuelTypes on o.FuelTypeId equals f.ID
                          join u in db.STPServicesUnitTypes on o.UnitTypeId equals u.ID
                          select new
                          {
                              OrderId = o.OrderId,
                              CustomerName = o.CustomerName,
                              Contact = o.Contact,
                              Address = o.Address,
                              Description = s.ServiceTypeName,
                              TimeRange = t.TimeRange,
                              preferredDate = o.preferredDate,
                              status = st.Description,
                              FuelType =f.Options,
                              unitType =u.Options
                          }).ToList();
            return View();
        }
        public ActionResult Maps()
        {
            return View();
        }
    }
}

WebAppSastiServices/Controllers/SupplierDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppSastiServices.Controllers
{
    public class SupplierDashboardController : Controller
    {
        // GET: SupplierDashboard
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Email()
        {
            return View();
        }
        public ActionResult SupplierProfile()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult LockScreen()
        {
            return View();
        }
        public ActionResult Invoice()
        {
            return View();
        }
    }
}

WebAppSastiServices/Views/AdminDashboard/AdminProfile.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutDashboardAdmin.cshtml";
}

<!-- start page inner -->
<div class="page-inner no-page-title">
    <!-- start page main wrapper -->
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-3">
                <div class="card card-white">
                    <div class="card-heading clearfix">
                        <h4 class="card-title">User Profile</h4>
                    </div>
                    <div class="card-body user-profile-card">
                        <img src="~/img/Dashboard/avatars/profile.jpg" class="user-profile-image rounded-circle" alt="" />
                        <h4 class="text-center m-t-lg">Keir Prestonly</h4>
                        <p class="text-center">UI/UX Designer</p>
                        <hr>
                        <ul class="list-unstyled text-center">
                            <li>
                                <p><i class="fas fa-map-marker-alt m-r-xs"></i>London</p>
                            </li>
                            <li>
                                <p><i class="far fa-paper-plane m-r-xs"></i><a href="#">example@mail.com</a></p>
                            </li>
                        </ul>
                        <hr>
                        <button class="btn btn-info btn-block">Follow</button>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-white">
                    <div class="card-body">
                        <div class="post">
                            <textarea class="form-control" placeholder="Post" rows="4"></textarea>
                            <div class="post-options">
                                <a href="#"><i class="fa fa-camera"></i></a>
                                <a href="#"><i class="fas fa-video"></i></a>
                                <a href="#"><i class="fa fa-music"></i></a>
                                <button class="btn btn-outline-primary float-right">Post</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="profile-timeline">
                    <ul class="list-unstyled">
                        <li class="timeline-item">
                            <div class="card card-white">
                                <div class="card-body">
                                    <div class="timeline-item-header">
                                        <img src="~/img/Dashboard/avatars/post01.jpg" alt="" />
                                        <p>jilack smith <span>posted a status</span></p>
                                        <small>3 hours ago</small>
                                    </div>
                                    <div class="timeline-item-post">
                                        <p>Inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur.</p>
                                        <div class="timeline-options">
                                            <a href="#"><i class="fa fa-thumbs-up"></i> Like (15)</a>
                                            <a href="#"><i class="fa fa-comment"></i> Comment (4)</a>
                                            <a href="#"><i class="fa fa-share"></i> Share (6)</a>
                                        </div>
                                        <div class="timeline-comment">
                                            <div class="timeline-comment-header">
                                                <img src="~/img/Dashboard/avatars/post03.jpg" alt="" />
                                                <p>Jamara Karle <small>1 hour ago</small></p>
                                            </div>
                                            <p class="timeline-comment-text">Dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.</p>
                                        </div>
                                        <div class="timeline-comment">
                                            <div class="timeline-comment-header">
                                                <img src="~/img/Dashboard/avatars/post04.jpg" alt="" />
                                                <p>Keir Prestonly <small>3 hours ago</small></p>
                                            </div>
                                            <p class="timeline-comment-text">Nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.</p>
                                        </div>
                                        <textarea class="form-control" placeholder="Replay"></textarea>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-item">
                            <div class="card card-white">
                                <div class="card-body">
                                    <div class="timeline-item-header">
                                        <img src="~/img/Dashboard/avatars/post02.jpg" alt="" />
                                        <p>Finley Walkeror <span>uploaded a photo</span></p>
                                        <small>7 hours ago</small>
                                    </div>
                                    <div class="timeline-item-post">
                                        <p>Aperiam, eaque ipsa quae ab illo inventore</p>
                                        <img src="~/img/Dashboard/post-img01.jpg" alt="" />
                                        <div class="timeline-options">
                                            <a href="#"><i class="fa fa-thumbs-up"></i> Like (22)</a>
                                            <a href="#"><i class="fa fa-comment"></i> Comment (7)</a>
                                            <a href="#"><i class="fa fa-share"></i> Share (9)</a>
                                        </div>
                                        <div class="timeline-comment">
                                            <div class="timeline-comment-header">
                                                <img src="~/img/Dashboard/avatars/post05.jpg" alt="" />
                                                <p>Stepha Kruse <small>1 hour ago</small></p>
                                            </div>
                                            <p class="timeline-comment-text">Voluptas sit aspernatur aut odit aut fugit.</p>
                                        </div>
                                        <textarea class="form-control" placeholder="Replay"></textarea>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card card-white">
                    <div class="card-heading clearfix">
                        <h4 class="card-title">Suggestions</h4>
                    </div>
                    <div class="card-body">
                        <div class="team">
                            <div class="team-member">
                                <div class="online on"></div>
                                <img src="~/img/Dashboard/avatars/sug01.jpg" alt="" />
                            </div>
                            <div class="team-member">
                                <div class="online on"></div>
                                <img src="~/img/Dashboard/avatars/sug02.jpg" alt="" />
                            </div>
                            <div class="team-member">
                                <div class="online off"></div>
                                <img src="~/img/Dashboard/avatars/sug03.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card card-white">
                    <div class="card-heading clearfix">
                        <h4 class="card-title">Some Info</h4>
                    </div>
                    <div class="card-body">
                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis architecto.</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Row -->
    </div>
    <!-- end page main wrapper -->
    <div class="page-footer">
        <p>Copyright &copy;
        <script>document.write(new Date().getFullYear())</script> Crizal All rights reserved.</p>
    </div>
</div>
<!-- end page inner -->

WebAppSastiServices/Views/AdminDashboard/Email.cshtml
@{
    ViewBag.Title = "Email";
    Layout = "~/Views/Shared/_LayoutDashboardAdmin.cshtml";
}
<!-- start page inner -->
<div class="page-inner">
    <div class="page-title">
        <h3 class="breadcrumb-header">Email</h3>
    </div>
    <!-- start page main wrapper -->
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="input-group email-search">
                    <input type="text" class="form-control" placeholder="Search for an email">
                    <span class="input-group-prepend last">
                        <button class="btn btn-primary" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>
        <!-- Row -->
        <div class="cross-page-line"></div>
        <div class="row">
            <div class="col-md-2">
                <div class="email-actions">
                    <a href="#" class="btn btn-primary compose">Compose</a>
                </div>
                <div class="email-menu">
                    <ul class="list-unstyled">
                        <li class="active"><a href="#"><i class="icon-inbox"></i><span>Inbox</span></a></li>
                        <li><a href="#"><i class="icon-send"></i><span>Sent</span></a></li>
                        <li><a href="#"><i class="icon-mail_outline"></i><span>Drafts</span></a></li>
                        <li><a href="#"><i class="icon-error"></i><span>Spam</span></a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="icon-delete"></i><span>Trash</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <div class="email-list">
                    <ul class="list-unstyled">
                        <li class="active">
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/1.jpg" alt="">
                                        <span class="author-name">Jamara Karle</span>
                                        <span class="email-date">8m ago</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Eque porro quisquam est, qui dolorem ipsum quia posuere eget
                                        </span>
                                        <span class="email-text">
                                            Tempora incidunt ut labore et dolore magnam aliquam quaerat
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/2.jpg" alt="">
                                        <span class="author-name">Keir Prestonly</span>
                                        <span class="email-date">5:55pm</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Mollit anim id est laborum perspiciatis unde
                                        </span>
                                        <span class="email-text">
                                            Voluptate velit esse cillum dolore eu fugiat nulla
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/3.jpg" alt="">
                                        <span class="author-name">Finley Walkeror</span>
                                        <span class="email-date">12 Mar 2019</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Nemo enim ipsam voluptatem quia voluptas sit aspernatur
                                        </span>
                                        <span class="email-text">
                                            Reprehenderit in voluptate velit esse cillum
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/4.jpg" alt="">
                                        <span class="author-name">Stepha Kruse</span>
                                        <span class="email-date">10 Mar 2019</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Duis aute irure dolor in reprehenderit in volu
                                        </span>
                                        <span class="email-text">
                                            Fugiat nulla pariatur excepteur sint occaecat
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/5.jpg" alt="">
                                        <span class="author-name">Alivin Corondo</span>
                                        <span class="email-date">08 Mar 2019</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Tempora incidunt ut labore et dolore magnam aliquam
                                        </span>
                                        <span class="email-text">
                                            Magni dolores eos qui ratione voluptatem sequi nesciunt
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="email-list-item">
                                    <div class="email-author">
                                        <img src="~/img/Dashboard/email/6.jpg" alt="">
                                        <span class="author-name">Dunican keithly</span>
                                        <span class="email-date">07 Mar 2019</span>
                                    </div>
                                    <div class="email-info">
                                        <span class="email-subject">
                                            Officia deserunt mollit anim id est laborum
                                        </span>
                                        <span class="email-text">
                                            Exercitation ullamco laboris nisi ut aliquip
                                        </span>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-7">
                <div class="email-actions">
                    <a href="#" class="btn btn-primary"><i class="fas fa-reply"></i> Reply</a>
                    <a href="#" class="btn btn-secondary"><i class="fas fa-forward"></i> Forward</a>
                    <a href="#" class="btn btn-success"><i class="fas fa-check-double"></i> Mark as read</a>
                    <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
                </div>
                <div class="email">
                    <div class="email-header">
                        <div class="email-title">
                            <p>Eque porro quisquam est, qui dolorem ipsum quia posuere eget</p>
                        </div>
                        <span class="divider"></span>
                        <div class="email-author">
                            <img src="~/img/Dashboard/email/1.jpg" alt="">
                            <span class="author-name">Jamara.karle@test.com</span>
                            <span class="email-date">4:14pm</span>
                        </div>
                        <span class="divider"></span>
                    </div>
                    <div class="email-body">
                        <span>
                            Dear Sir/Madam,<br><br>
                            Exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore.<br><br>
                            Waiting your reply ASAP,<br>
                            Thanks in advance.
                        </span>
                    </div>
                    <div class="email-reply">
                        <div class="summernote"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Row -->
    </div>
    <!-- end page main wrapper -->
    <div class="page-footer">
        <p>Copyright &copy;
        <script>document.write(new Date().getFullYear())</script> Crizal All rights reserved.</p>
    </div>
</div>
<!-- end page inner -->

WebAppSastiServices/Views/AdminDashboard/LatestActOrders.cshtml
@model IEnumerable<WebAppSastiServices.Models.DB.STPOrder>
@{
    Layout = null;
}
<html>
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js">
</script>
</head>
<body>

    


</body>
</html>

WebAppSastiServices/Views/AdminDashboard/Supplier.cshtml
@{
    ViewBag.Title = "Supplier";
    Layout = "~/Views/Shared/_LayoutDashboardAdmin.cshtml";
}


<!-- start page inner -->
<div class="page-inner">
    <div class="page-title">
        <h3 class="breadcrumb-header">Supplier</h3>
    </div>
    <!-- start page main wrapper -->
    <div id="main-wrapper">
        <div class="row">
            <a href="@Url.Action("GeneratorsIndex","SupplierDashboard")" class="col-xl-4 col-lg-6 col-md-6">
                <div class="card card-white stats-widget">
                    <div class="card-body">
                        <div class="float-left">
                            <span class="stats-number">Generators</span>
                            <p class="stats-info">813 Orders</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="progress mb-0 mt-3">
                            <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                <span class="sr-only">40% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="@Url.Action("ACIndex","SupplierDashboard")" class="col-xl-4 col-lg-6 col-md-6">
                <div class="card card-white stats-widget">
                    <div class="card-body">
                        <div class="float-left">
                            <span class="stats-number">Air Conditioners</span>
                            <p class="stats-info">178 Orders</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="progress mb-0 mt-3">
                            <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
                                <span class="sr-only">20% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="@Url.Action("UPSIndex","SupplierDashboard")" class="col-xl-4 col-lg-6 col-md-6">
                <div class="card card-white stats-widget">
                    <div class="card-body">
                        <div class="float-left">
                            <span class="stats-number">UPS</span>
                            <p class="stats-info">888 Orders</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="progress mb-0 mt-3">
                            <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;">
                                <span class="sr-only">70% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="@Url.Action("SolarSysIndex","SupplierDashboard")" class="col-xl-4 col-lg-6 col-md-6">
                <div class="card card-white stats-widget">
                    <div class="card-body">
                        <div class="float-left">
                            <span class="stats-number">Solar System</span>
                            <p class="stats-info">58 Orders</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="progress mb-0 mt-3">
                            <div class="progress-bar bg-success" role="progressbar" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100" style="width: 58%;">
                                <span class="sr-only">58% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="@Url.Action("CCTVIndex","SupplierDashboard")" class="col-xl-4 col-lg-6 col-md-6">
                <div class="card card-white stats-widget">
                    <div class="card-body">
                        <div class="float-left">
                            <span class="stats-number">CCTV</span>
                            <p class="stats-info">34 Orders</p>
                        </div>
                        <div class="clearfix"></div>
                        <div class="progress mb-0 mt-3">
                            <div class="progress-bar bg-primary" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                <span class="sr-only">80% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>


    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card card-white" style="height: 400px;">
                <div class="card-heading clearfix">
                    <h4 class="card-title">Our Users</h4>
                </div>
                <div class="card-body">
                    <div id="chart1">
                        <svg style="height:100%;width:100%"></svg>
                    </div>
                </div>
            </div>
        </div>

    </div>